version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - pip3 install aws-sam-cli -U
  build:
    commands:
      - sam build --debug
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged_raw.yaml
  post_build:
    commands:
      # Use timestamp to force update of ApiGatewayCreateDeploymentCustomResource
      - BUILD_TIMESTAMP=$(date '+%s')
      - envsubst '${BUILD_TIMESTAMP}' < packaged_raw.yaml > packaged.yaml
reports:
  test-results:
    files: # Specify the location of test report files
      - '**/*'
    file-format: 'JUNITXML' # Format of the test report
    base-directory: 'build/reports' # Base directory where the reports are located
artifacts:
  files:
    - packaged.yaml