AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS
  
  SAM Template for NVA NVI API

Globals:
  Function:
    Environment:
      Variables:
        SEARCH_INFRASTRUCTURE_API_URI: !Ref SearchInfrastructureApiUri
        SEARCH_INFRASTRUCTURE_AUTH_URI: !Ref SearchInfrastructureAuthUri

Parameters:
  CognitoAuthorizationUri:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/NVA/CognitoUri'
  ApiDomain:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: The Api domain
    Default: /NVA/ApiDomain
  EventBusName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /NVA/Events/EventsBusName
  EventBusArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /NVA/Events/EventsBusArn
  ResourcesBucket:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /NVA/Events/PersistedEntriesBucketName
  NewCandidateQueueName:
    Type: String
    Default: NewCandidateQueue
  NewCandidateDLQName:
    Type: String
    Default: NewCandidateDLQ
  SearchInfrastructureApiUri:
    Type: String
    Description: URI to external search infrastructure API (SWS).
    Default: 'https://api.sws.aws.sikt.no'
  SearchInfrastructureAuthUri:
    Type: String
    Description: URI to auth for external search infrastructure API (SWS).
    Default: 'https://sws-auth.auth.eu-west-1.amazoncognito.com'

Resources:
  #=============================== SQSs ============================================================
  NewCandidateQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref NewCandidateQueueName
  NewCandidateDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref NewCandidateDLQName
      MessageRetentionPeriod: 43200

  #============================= Permissions =======================================================
  NvaNviRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [ lambda.amazonaws.com ]
            Action: [ 'sts:AssumeRole' ]
      Policies:
        - PolicyName: readFromS3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - events:*
                  - secretsmanager:*
                Resource: '*'
        - PolicyName: Events
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:*
                  - sqs:SendMessage
                  - sqs:GetQueueUrl
                Resource:
                  - !Ref EventBusArn
                  - !GetAtt NewCandidateQueue.Arn
                  - !GetAtt NewCandidateDLQ.Arn
        - PolicyName: writeLog
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*'
        - PolicyName: readSearchInfrastructureSecret
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:SearchInfrastructureCredentials*'
        - PolicyName: readSqs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:*
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: !GetAtt NewCandidateQueue.Arn

  #============================= Handlers ==========================================================
  EvaluateNVICandidateHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nvi-evaluator
      Handler: no.sikt.nva.nvi.evaluator.EvaluateNviCandidateHandler::handleRequest
      Runtime: java17
      Role: !GetAtt NvaNviRole.Arn
      Timeout: 3
      MemorySize: 1536
      Environment:
        Variables:
          BACKEND_CLIENT_AUTH_URL: !Ref CognitoAuthorizationUri
          BACKEND_CLIENT_SECRET_NAME: 'BackendCognitoClientCredentials'
          API_HOST: !Ref ApiDomain
          EXPANDED_RESOURCES_BUCKET: !Ref ResourcesBucket
          CANDIDATE_QUEUE_NAME: !Ref NewCandidateQueueName
          CANDIDATE_DLQ_NAME: !Ref NewCandidateDLQName
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBusName
            Pattern:
              detail-type:
                - Lambda Function Invocation Result - Success
              detail:
                responsePayload:
                  topic: [ "PublicationService.ExpandedEntry.Persisted" ]
#      EventInvokeConfig:
#        DestinationConfig:
#          OnSuccess:
#            Type: SQS
#            Destination: !GetAtt NewCandidateQueue.Arn
#          OnFailure:
#            Type: SQS
#            Destination: !GetAtt NewCandidateDLQ.Arn

  IndexNviCandidateHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: index-handlers
      Handler: no.sikt.nva.nvi.index.IndexNviCandidateHandler::handleRequest
      Runtime: java17
      Role: !GetAtt NvaNviRole.Arn
      Environment:
        Variables:
          EXPANDED_RESOURCES_BUCKET: !Ref ResourcesBucket
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt NewCandidateQueue.Arn