AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS
  
  SAM Template for NVA NVI API

Globals:
  Function:
    Timeout: 20
    Runtime: java17
    MemorySize: 1536
    Environment:
      Variables:
        SEARCH_INFRASTRUCTURE_API_HOST: !Ref SearchInfrastructureApiHost
        SEARCH_INFRASTRUCTURE_AUTH_URI: !Ref SearchInfrastructureAuthUri
  Api:
    Cors:
      AllowMethods: "'PUT, GET,OPTIONS,DELETE,POST'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Location'"
      AllowOrigin: "'*'"

Parameters:
  CognitoAuthorizerArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Reference to Cognito UserPool for the stage
    Default: CognitoAuthorizerArn
  CognitoAuthorizationUri:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/NVA/CognitoUri'
  ApiDomain:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: The Api domain
    Default: /NVA/ApiDomain
  EventBusName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /NVA/Events/EventsBusName
  EventBusArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /NVA/Events/EventsBusArn
  ResourcesBucket:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /NVA/Events/PersistedEntriesBucketName
  NewCandidateQueueName:
    Type: String
    Default: NewCandidateQueue
  NewCandidateDLQName:
    Type: String
    Default: NewCandidateDLQ
  SearchInfrastructureApiHost:
    Type: String
    Description: Host of external search infrastructure API (SWS).
    Default: 'https://api.sws.aws.sikt.no'
  SearchInfrastructureAuthUri:
    Type: String
    Description: URI to auth for external search infrastructure API (SWS).
    Default: 'https://sws-auth.auth.eu-west-1.amazoncognito.com'
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain
    Default: scientific-index
  Suffix:
    Type: String
    Default: ''
    Description: Suffix used for naming resources for feature branches to avoid conflicts.

Conditions:
  WithSuffix: !Not [ !Equals [ !Ref Suffix, '' ] ]

Resources:

  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup

  #=============================== SQSs ============================================================
  NewCandidateQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref NewCandidateQueueName
  NewCandidateDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref NewCandidateDLQName
      MessageRetentionPeriod: 43200

  #============================= Permissions =======================================================
  NvaNviRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [ lambda.amazonaws.com ]
            Action: [ 'sts:AssumeRole' ]
      Policies:
        - PolicyName: readFromS3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - events:*
                  - secretsmanager:*
                Resource: '*'
        - PolicyName: Events
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:*
                  - sqs:SendMessage
                  - sqs:GetQueueUrl
                Resource:
                  - !Ref EventBusArn
                  - !GetAtt NewCandidateQueue.Arn
                  - !GetAtt NewCandidateDLQ.Arn
        - PolicyName: writeLog
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*'
        - PolicyName: readSqs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:*
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: !GetAtt NewCandidateQueue.Arn
        - PolicyName: readSecret
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: '*'
        - PolicyName: invokeFunction
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: '*'

  #============================= Roles ==========================================================
  ScientificIndexApi:
    Type: AWS::Serverless::Api
    Properties:
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{ "apiId": "$context.apiId", "requestId": "$context.requestId", "requestTime": "$context.requestTime", "requestTimeEpoch": "$context.requestTimeEpoch", "httpMethod": "$context.httpMethod", "path": "$context.path", "status": "$context.status",  "error.message": "$context.error.message" }'
      StageName: Prod
      EndpointConfiguration: REGIONAL
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: ./docs/openapi.yaml

  #===========================BasePathMappings========================================================
  NviBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !If
        - WithSuffix
        - !Sub ${CustomDomainBasePath}-${Suffix}
        - !Sub ${CustomDomainBasePath}
      DomainName: !Ref ApiDomain
      RestApiId: !Ref ScientificIndexApi
      Stage: !Ref ScientificIndexApi.Stage

  #============================= Handlers ==========================================================
  EvaluateNVICandidateHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nvi-evaluator
      Handler: no.sikt.nva.nvi.evaluator.EvaluateNviCandidateHandler::handleRequest
      Runtime: java17
      Role: !GetAtt NvaNviRole.Arn
      Timeout: 30
      MemorySize: 1536
      Environment:
        Variables:
          BACKEND_CLIENT_AUTH_URL: !Ref CognitoAuthorizationUri
          BACKEND_CLIENT_SECRET_NAME: 'BackendCognitoClientCredentials'
          API_HOST: !Ref ApiDomain
          EXPANDED_RESOURCES_BUCKET: !Ref ResourcesBucket
          CANDIDATE_QUEUE_NAME: !Ref NewCandidateQueueName
          CANDIDATE_DLQ_NAME: !Ref NewCandidateDLQName
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBusName
            Pattern:
              detail-type:
                - Lambda Function Invocation Result - Success
              detail:
                responsePayload:
                  topic: [ "PublicationService.ExpandedEntry.Persisted" ]

  IndexNviCandidateHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: index-handlers
      Handler: no.sikt.nva.nvi.index.IndexNviCandidateHandler::handleRequest
      Timeout: 30
      MemorySize: 1536
      Role: !GetAtt NvaNviRole.Arn
      Environment:
        Variables:
          EXPANDED_RESOURCES_BUCKET: !Ref ResourcesBucket

  UpsertNviCandidateHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: index-handlers
      Handler: no.sikt.nva.nvi.handlers.IndexNviCandidateHandler::handleRequest
      Timeout: 30
      MemorySize: 1536
      Role: !GetAtt NvaNviRole.Arn


  DeleteNviCandidateHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: index-handlers
      Handler: no.sikt.nva.nvi.index.DeleteNviCandidateHandler::handleRequest
      Timeout: 30
      MemorySize: 1536
      Role: !GetAtt NvaNviRole.Arn

  SearchNviCandidatesHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: index-handlers
      Handler: no.sikt.nva.nvi.index.SearchNviCandidatesHandler::handleRequest
      Role: !GetAtt NvaNviRole.Arn
      Timeout: 600
      MemorySize: 1536
      AutoPublishAlias: live
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
          API_HOST: !Ref ApiDomain
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /candidates
            Method: get
            RestApiId: !Ref ScientificIndexApi

  DeleteNviCandidateIndexHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda that deletes scientific index. Needs to be run manually from Test
      CodeUri: index-handlers
      Handler: no.sikt.nva.nvi.index.DeleteNviIndexHandler::handleRequest
      Role: !GetAtt NvaNviRole.Arn

  # ======================= API HANDLERS ========================

  FetchNviCandidateHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nvi-rest
      Handler: no.unit.nva.nvi.fetch.FetchNviCandidateHandler::handleRequest
      Role: !GetAtt NvaNviRole.Arn
      Timeout: 600
      MemorySize: 1536
      AutoPublishAlias: live
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
          API_HOST: !Ref ApiDomain
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /candidates/{candidateIdentifier}
            Method: get
            RestApiId: !Ref ScientificIndexApi
