plugins {
    id 'nva.nvi.java-conventions'
}

dependencies {
    api(nvaCatalog.jackson.databind)
    api(nvaCatalog.jena.core)
    api(nvaCatalog.jena.shacl)
    api(nvaCatalog.slf4j.api)
    implementation(libs.jakarta.json.api)
    implementation(nvaCatalog.jena.arq)
    implementation(nvaCatalog.titanium.json.ld)
    implementation(nvaLibs.core)
    runtimeOnly(libs.parsson)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaLibs.json)
}
