package no.sikt.nva.nvi.report.model.institutionreport;

import no.sikt.nva.nvi.report.model.Header;

public enum ReportHeader implements Header {
  ARSTALL,
  NVAID,
  PUBLIKASJONSFORM,
  PUBLISERINGSKANAL,
  PUBLISERINGSKANALTYPE,
  PRINT_ISSN,
  PUBLISERINGSKANALNAVN,
  KVALITETSNIVAKODE,
  PERSONLOPENR,
  SEKTORKODE,
  STATUS_RBO,
  DBH_INSTITUSJONSKODE,
  DBH_FAKULTETSKODE,
  DBH_AVDELINGSKODE,
  INSTITUSJONSNR,
  AVDNR,
  UNDAVDNR,
  GRUPPENR,
  INSTITUSJON,
  INSTITUSJON_ID,
  ETTERNAVN,
  FORNAVN,
  TITTEL,
  STATUS_KONTROLLERT,
  RAPPORTSTATUS,
  VEKTINGSTALL,
  FAKTORTALL_SAMARBEID,
  FORFATTERDEL,
  TENTATIVE_PUBLISERINGSPOENG,
  PUBLISERINGSPOENG
}
