plugins {
    id 'nva.nvi.java-conventions'
}

dependencies {
    api(nvaCatalog.jackson.databind)
    api(nvaLibs.auth)
    api(nvaLibs.identifiers)
    implementation(nvaCatalog.datafaker)
    implementation(nvaCatalog.slf4j.api)
    implementation(nvaLibs.core)
    implementation(nvaLibs.testutils)
}
