plugins {
    id 'nva.nvi.java-conventions'
}

dependencies {
    api(nvaCatalog.aws.lambda.core)
    api(nvaCatalog.aws.lambda.events)
    api(nvaCatalog.aws.sdk2.eventbridge)
    api(nvaCatalog.aws.sdk2.s3)
    api(nvaCatalog.jackson.annotations)
    api(nvaCatalog.jackson.core)
    api(nvaCatalog.jackson.databind)
    api(nvaLibs.clients)
    api(nvaLibs.core)
    api(nvaLibs.eventhandlers)
    api(nvaLibs.json)
    api(project(':migration-service'))
    api(project(':nvi-commons'))
    implementation(nvaCatalog.aws.sdk2.dynamo)
    implementation(nvaCatalog.aws.sdk2.http.client)
    implementation(nvaCatalog.aws.sdk2.sdk.core)
    implementation(nvaCatalog.aws.sdk2.urlconnection)
    implementation(nvaCatalog.jackson.dataformat.csv)
    implementation(nvaCatalog.log4j.core)
    implementation(nvaCatalog.slf4j.api)
    implementation(nvaLibs.apigateway)
    implementation(nvaLibs.s3)
    implementation(project(':publication-service'))
    runtimeOnly(nvaCatalog.jena.arq)
    runtimeOnly(nvaCatalog.jena.core)
    runtimeOnly(nvaCatalog.log4j.api)
    runtimeOnly(nvaCatalog.log4j.slf4j.impl)
    testFixturesApi(nvaCatalog.aws.lambda.events)
    testFixturesApi(nvaCatalog.aws.sdk2.sns)
    testFixturesApi(project(':nvi-commons'))
    testFixturesApi(testFixtures(project(":nvi-commons")))
    testFixturesImplementation(nvaCatalog.aws.lambda.core)
    testFixturesImplementation(nvaLibs.core)
    testFixturesImplementation(nvaLibs.testutils)
    testFixturesImplementation(project(':nvi-test'))
    testImplementation(nvaCatalog.assertj.core)
    testImplementation(nvaCatalog.aws.sdk2.regions)
    testImplementation(nvaCatalog.aws.sdk2.sqs)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaCatalog.junit.jupiter.params)
    testImplementation(nvaCatalog.mockito.core)
    testImplementation(nvaLibs.identifiers)
    testImplementation(nvaLibs.logutils)
    testImplementation(nvaLibs.testutils)
    testImplementation(project(':nvi-test'))
    testImplementation(testFixtures(project(":nvi-commons")))
}
