package no.sikt.nva.nvi.index.report.model;

public enum Header {
  ARSTALL,
  NVAID,
  PUBLIKASJONSFORM,
  PUBLISERINGSKANAL,
  PUBLISERINGSKANALTYPE,
  PRINT_ISSN,
  PUBLISERINGSKANALNAVN,
  KVALITETSNIVAKODE,
  PERSONLOPENR,
  INSTITUSJON,
  INSTITUSJON_ID,
  INSTITUSJONSNR,
  AVDNR,
  UNDAVDNR,
  GRUPPENR,
  ETTERNAVN,
  FORNAVN,
  TITTEL,
  STATUS_KONTROLLERT,
  RAPPORTSTATUS,
  VEKTINGSTALL,
  FAKTORTALL_SAMARBEID,
  FORFATTERDEL,
  TENTATIVE_PUBLISERINGSPOENG,
  PUBLISERINGSPOENG
}
