PREFIX  nva: <https://nva.sikt.no/ontology/publication#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE {
  VALUES ?approvedType { nva:AcademicMonograph nva:AcademicChapter nva:AcademicArticle nva:AcademicLiteratureReview }

  ?publication a nva:Publication ;
               nva:status nva:PUBLISHED ;
               (<>|!<>)+/nva:publicationInstance/rdf:type ?approvedType .


  ?publicationDate a nva:PublicationDate ;
                   nva:year "__NVI_YEAR__" .

  OPTIONAL {
   SELECT distinct ?publisherLevel WHERE {
     ?publisher rdf:type ?type ;
                nva:level ?publisherLevel .
     FILTER(?type = nva:Publisher)
   }
  }

  OPTIONAL {
   SELECT distinct ?seriesLevel WHERE {
     ?publisher rdf:type ?type ;
                nva:level ?seriesLevel .
     FILTER(?type = nva:Series)
   }
  }

  OPTIONAL {
   SELECT distinct ?journalLevel WHERE {
         ?publisher rdf:type ?type ;
                    nva:level ?journalLevel .
         FILTER(?type = nva:Journal)
   }
  }

  BIND(IF (BOUND(?seriesLevel), ?seriesLevel, ?publisherLevel) AS ?seriesOrPublisherLevel)
  BIND(IF (BOUND(?journalLevel), ?journalLevel, ?seriesOrPublisherLevel) AS ?optionalLevel)
  BIND(IF (BOUND(?optionalLevel), ?optionalLevel, "0") AS ?level)

  VALUES ?channelType { nva:Publisher  nva:Series   nva:Journal }
  VALUES ?level {"1" "2"}
}